# Generated by Django 3.2.7 on 2021-09-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210922_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='symptom',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField(default='Not examined yet', max_length=500)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.appointment')),
            ],
        ),
    ]
