# Generated by Django 3.2.7 on 2021-09-18 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_doctorinfo_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.usersinfo'),
        ),
    ]
