# Generated by Django 3.2.7 on 2021-09-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_doctorinfo_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(blank=True, default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('hemoglobin', models.IntegerField()),
                ('platelets', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='currentAppintments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointments', models.IntegerField(blank=True, default=0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.doctorinfo')),
            ],
        ),
    ]
