# Generated by Django 3.2.7 on 2021-09-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210927_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='mobile_number',
            field=models.TextField(max_length=24),
        ),
    ]
